### ISSUE TITLE
Not on chrome web store

### ISSUE THREAD

**Issue by michael-harrison** [boost/combiner#61]
Not sure why but the plugin is no longer available on the Chrome Web Store

**Comment by paul-mesnilgrente** [comment]
Hi, that's because Chrome updated the manifest version at the start of the year. They un-published all extensions not complying with the new version.

I started a PR to update it https://github.com/boost/combiner/pull/43 but that's just early work and the compatibility with Firefox is a bit more complicated. Were you using this extension?

**Comment by michael-harrison** [comment]
@paul-mesnilgrente thanks for getting back to me so quickly.  
> Were you using this extension?

Yes we are using this with our team.  We have been installing it using the current released version via the developer mode in Chrome.  While not ideal it works for now.

**Comment by paul-mesnilgrente** [comment]
Awesome to know that you use the extension. I'll try to get some momentum on this at my company. I should be able to work on it on an R&D day. 

Can I ask what features you use?

**Comment by michael-harrison** [comment]
@paul-mesnilgrente 
> Awesome to know that you use the extension. I'll try to get some momentum on this at my company. I should be able to work on it on an R&D day.

That's great.  Let me know if you need any testing.  Would be happy to help.

> Can I ask what features you use?

We primarily use it for time recording for stories.  While it's good to have it on the various plugin stores, it might be worth getting exposure on the [Harvest Integrations](https://www.getharvest.com/integrations) and [Pivotal Tracker Integration](https://www.pivotaltracker.com/integrations) pages.  Not sure if they know about the work your doing.

P.S. We don't use Basecamp.

**Comment by paul-mesnilgrente** [comment]
I should be able to get it in the chrome webstore in the next 3 weeks.

**Comment by michael-harrison** [comment]
Thanks @paul-mesnilgrente that's now in the store with updates coming through
